development:
  adapter: mysql2
  reconnect: false
  database: fantasypolitics_development
  pool: 5
  timeout: 5000
  username: root
  password:
  port: 3306

test:
  adapter: mysql2
  reconnect: false
  database: fantasypolitics_test
  pool: 5
  timeout: 5000
  username: root
  password:
  port: 3306

production:
  adapter: mysql2
  reconnect: false
  database: fantasypolitics_production
  pool: 5
  timeout: 5000
  username: root
  password:
  port: 3306
